### ISSUE TITLE
Change UV mapping for cubes and cylinders

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#215] opened 2022-12-23 15:39 UTC
**Is your feature request related to a problem? Please describe.**
The current UV mapping for cubes and cylinders require all faces on a single file. It leads to huge amount of additional work for creating mahjong tiles, domino tiles, ganjifa cards etc.

**Describe the solution you'd like**
Change UV mapping to supporting single files for single faces.

**Comment by drwhut** [comment] 2022-12-23 17:08
Closing as this is a duplicate of #115.

**Closed by drwhut** 2022-12-23 17:08 UTC
