### ISSUE TITLE
[Feature request] Add object type “Scoreboards”

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#181] opened 2022-12-04 19:09 UTC
There can be cribbage scoreboards, euchre scoreboards, contract bridge scoreboard and more. Player names and tally marks can be drawn on them.

**Comment by drwhut** [comment] 2022-12-09 16:11
This is kind of a duplicate of #143, which has already been closed.

This could be done with #144 potentially, but the engine needs to be updated for that to be implemented.

For now, you can either draw on the table for tallies, or use the notebook to keep track of scores.

**Closed by drwhut** 2022-12-09 16:11 UTC
