### ISSUE TITLE
Cards temporarily submerged after throwing

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#264] opened 2023-04-04 03:22 UTC
Cards submerge under the table surface for a while after being thrown and are rotating. I remember in the earlier versions, when I used Vector3 with the thickness of 2mm, they were working well.

**Comment by drwhut** [comment] 2023-04-04 09:12
Think this is a duplicate of #117.

**Closed by drwhut** 2023-04-04 09:12 UTC
