### ISSUE TITLE
Crash/freeze when navigating the Objects menu

### ISSUE THREAD

**Issue by SamTheBlow** [drwhut/tabletop-club#310] opened 2023-11-23 00:49 UTC
**Describe the bug**
When going through pages in the Objects menu, the game is highly prone to crashing and freezing.

**To Reproduce**
1. Click on 'Singleplayer'
2. Click on 'Objects'
3. Spam click on the arrows to go to the previous/next page
4. The game consistently crashes or freezes in under a minute

**Expected behavior**
The game is expected to not crash or freeze :)

**Screenshots**
Spam click these arrows here:
![bug_report](https://github.com/drwhut/tabletop-club/assets/125810628/20fb9d0f-c91e-483f-b318-d71fa711abe3)

**Environment**
Linux (Ubuntu)

**Version**
v0.1.2

**Additional context**
You don't even need to click at a fast rate. I found that it consistently crashes/freezes even when clicking on the arrows once every two seconds.
Another note is that sometimes it crashes, sometimes it freezes. I don't know why that is.
One final note is that for some reason, I can't find the log file, if there is one.

**Comment by drwhut** [comment] 2023-11-23 05:20
I'll mark this as a duplicate of #216, but yeah I've had this happen to me a few times as well completely at random, and it's extremely difficult to debug. Hopefully with the new objects menu UI coming in v0.2.0 (see #268), this problem should be completely eliminated :crossed_fingers:

**Closed by drwhut** 2023-11-23 05:20 UTC
