### ISSUE TITLE
Bug: Unable to drop smaller objects

### ISSUE THREAD

**Issue by elmodor** [drwhut/tabletop-club#145] opened 2022-11-30 10:06 UTC
**Describe the bug**
It's not possible to drop smaller objects without them jittering/moving around.

**To Reproduce**
1. Spawn D6
2. Transform with scale 0.5
3. Unable to drop dice without it moving

**Expected behavior**
Able to drop (smaller/all) objects without them jittering/moving around when they should drop straight down.

**Screenshots**
These objects are dropped from the smallest possible height.
[dice_drop.webm](https://user-images.githubusercontent.com/2340082/204767585-62ce935a-d652-4360-8095-8bb63beeef0f.webm)
[token_drop.webm](https://user-images.githubusercontent.com/2340082/204767594-caec3af7-e087-4249-8feb-9797df4511d2.webm)

**Version**
v0.1.0 Beta 1

**Additional Notes**
The jitter is also on larger objects - on dice with scale 1 1 1. It's just less noticeable. But even normal dice are very difficult to pick up and drop again without them changing values. There are many games where you roll -> pickup dice -> place dice somewhere.

Maybe related to #117

**Comment by elmodor** [comment] 2022-11-30 10:08
The jitter also appears when larger dices are on cards:
[dice_on_card.webm](https://user-images.githubusercontent.com/2340082/204767924-0173f1e0-a0be-48c9-926d-ba0b4b2332de.webm)

**Comment by drwhut** [comment] 2022-12-02 13:59
This is a known issue with Godot, unfortunately.

Closing as this is a duplicate of #50.

**Closed by drwhut** 2022-12-02 13:59 UTC
