### ISSUE TITLE
Cannot open Tabletop Club.app on MacOS

### ISSUE THREAD

**Issue by thmquan** [drwhut/tabletop-club#283] opened 2023-05-04 07:19 UTC
**Describe the bug**
I cannot open the _**Tabletop Club.app**_ on MacOS Ventura 13.3.1(a). Whenever I try, MacOS says that the file is damaged and cannot be opened. It would then only allow me to move the file to the trash.

**To Reproduce**
1. Download the file from any browser.
2. Extract the zip file.
3. Open the .app file.
4. See error.

**Expected behavior**
I expected the **_Tabletop Club.app_** file to open without any issue.

**Screenshots**
<img width="285" alt="image" src="https://user-images.githubusercontent.com/112092112/236136345-309450c4-8a3b-49ea-a6dd-f98e4e45239d.png">

**Environment**
e.g. MacOS Ventura 13.3.1(a)

**Version**
e.g. v0.1.0

**Comment by drwhut** [comment] 2023-05-04 13:21
Yeah, unfortunately you will not be able to launch the game normally due to the fact that I do not own an Apple Developer Certificate - but it can still be opened relatively easily, I have instructions that should hopefully work [in the other thread](https://github.com/drwhut/tabletop-club/issues/282#issuecomment-1534761541).

Since this is technically a duplicate of #282, I'll close this issue for now and keep all discussion surrounding running the game on macOS there.

**Closed by drwhut** 2023-05-04 13:21 UTC
