### ISSUE TITLE
Bug Linux: TabletopClub folder in home directory (assets)

### ISSUE THREAD

**Issue by elmodor** [drwhut/tabletop-club#109] opened 2022-11-27 16:51 UTC
**Describe the bug**
On Linux, when starting TabletopClub it creates a "TabletopClub" folder in the home directory (\~/TabletopClub) with "assets" and "saves" folder inside. 
When saving, the save files are stored in \~/TabletopClub/saves  
However, the assets folder (\~/TabletopClub/assets/) is not used/packed up as asset folder location. This is also documented here:
https://tabletop-club.readthedocs.io/en/latest/custom_assets/asset_packs/asset_pack_structure.html#locations-for-asset-packs (no \~/TabletopClub/assets is mentioned)

**To Reproduce**
1. Start TabletopClub
2. Exit again
3. Put custom assets inside \~/TabletopClub/assets/
4. Start TabletopClub again, no custom assets are imported/available

**Expected behavior**
I would expect that either: 
- No \~/TabletopClub/assets/ folder is created (only the save folder should be there) because it is not picked up by the importer
- Change the importer to also import assets from \~/TabletopClub/assets/

**Environment**
Arch Linux

**Version**
v0.1.0 Beta 1

**Comment by drwhut** [comment] 2022-11-27 20:13
So I've tried my best to replicate this - the game should create the `assets/` and `saves/` folders in what your OS considers to be your "Documents" folder. For Linux, this is whatever the output of this command is:
```bash
$ xdg-user-dir DOCUMENTS
/home/user/Documents
```

From the report, I assume your "Documents" folder has been assigned to your home folder? You may want to run the command yourself just to confirm.

So to try and replicate your setup, I created a new user on my system and set it's "Documents" folder to `/home/user`. It created the folders in the same locations you described, but the game managed to import assets from the `/home/user/TabletopClub/assets` folder just fine... are you sure the assets you put in that folder were not erroneous?

**Comment by elmodor** [comment] 2022-11-27 21:45
The assets are valid since they do work inside the assets folder.  

I think the problem here is that I do not use a desktop environment and I do not have xdg-user-dirs installed and only a few XDG_ vars are set.  
Testing around a bit more it seems that it doesn't place the TabletopClub folder inside my home directory but inside the games directory (next to TabletopClub.x86_64) - probably because my xdg path are incorrect/missing. 


However, I discovered a discrepancy between the asset directories.
In AssetDB.gd the asset dirs are set specifically to:
```
const ASSET_DIR_PREFIXES = [
	".",
	"..",
	"{EXEC_DIR}/../Resources", # macOS workaround.
	"{DOWNLOADS}/TabletopClub",
	"{DOCUMENTS}/TabletopClub",
	"{DESKTOP}/TabletopClub"
]
```
But ImportAssets.gd calls 
```
var assets_dir = Global.get_output_subdir("assets")
```
Which is basically:
```
func get_output_subdir(subfolder: String) -> Directory:
	var dir = Directory.new()
	
	if dir.open(OS.get_system_dir(OS.SYSTEM_DIR_DOCUMENTS)) != OK:
		if dir.open("user://") != OK:
```
And the directory that is set by this function is:
```
Created assets directory at '/home/USER/TabletopClub/TabletopClub/assets'.
```

So the correct way I think would be that the directory returned by get_output_subdir called by ImportAssets.gd  is also added to the ASSET_DIR_PREFIXES.

**Comment by drwhut** [comment] 2022-11-28 10:02
Hmm... I'm still confused as to why both paths are different, from looking at the source code both `Global.get_output_subdir("assets")` and what `"{DOCUMENTS}/TabletopClub"` turns into should in your case, be `/home/USER/TabletopClub/TabletopClub/assets`, since the engine thinks your "Documents" folder is in your game directory. (it's worth mentioning for the `ASSET_DIR_PREFIXES` array that `"/assets"` is appended to each of the elements)

- You mentioned in the original post that `~/TabletopClub/assets` and `~/TabletopClub/saves` folders were made - is that still the case? I'm just wondering since you mentioned the game posted this output:
```
Created assets directory at '/home/USER/TabletopClub/TabletopClub/assets'.
```
- Does placing custom assets in `/home/USER/TabletopClub/TabletopClub/assets` work for you?

**Comment by drwhut** [comment] 2022-11-28 12:06
Aha, think I understand what's going on - this is the code that runs `xdg-user-dir` in Godot, specifically from `platform/x11/os_x11.cpp`:
```cpp
	String pipe;
	List<String> arg;
	arg.push_back(xdgparam);
	Error err = const_cast<OS_X11 *>(this)->execute("xdg-user-dir", arg, true, nullptr, &pipe);
	if (err != OK) {
		return ".";
	}
	return pipe.strip_edges();
```

So when the game creates the assets folder in `Global.gd`, the path becomes `/home/user/TC/TabletopClub/assets`, whereas in `AssetDB.gd`, the path becomes `./TabletopClub/assets` - so the paths differ if the working directory is not where the game's executable is.

**Comment by elmodor** [comment] 2022-11-28 12:47
I don't think that is the issue.
```
Game dir: /home/user/TC/
/home/user/TabletopClub/assets/MyAssetPack/
/home/user/TC/TabletopClub/assets/MyAssetPack/
```
Both do not work
`/home/user/TC/assets/MyAssetPack` works.

I will try to setup a dev environment and maybe I can try to debug it myself what happens on my system and provide some more information.

**Comment by elmodor** [comment] 2022-11-28 15:44
Right, it's easier to do this with a debugger :smile: 

```
"{DOCUMENTS}/TabletopClub"
...
var path = prefix + "/assets"
# path: {DOCUMENTS}/TabletopClub/assets
path = path.replace("{DOCUMENTS}", OS.get_system_dir(OS.SYSTEM_DIR_DOCUMENTS))
# With: OS.get_system_dir(OS.SYSTEM_DIR_DOCUMENTS) = ""
```
Resulting path:
`/TabletopClub/assets`

So I would have said to replace with Os.get_system_dir() or "." if empty - but this would probably not work/break on other OS systems. Ideas?

**Comment by elmodor** [comment] 2022-11-28 16:04
How about adding:
`"./TabletopClub" # linux fallback`
to
```
const ASSET_DIR_PREFIXES = [
	".",
	"..",
        "./TabletopClub" # linux fallback
	"{EXEC_DIR}/../Resources", # macOS workaround.
	"{DOWNLOADS}/TabletopClub",
	"{DOCUMENTS}/TabletopClub",
	"{DESKTOP}/TabletopClub"
]
```

Might be a bit more clean than adding some twisted checks in `get_asset_paths` ?

**Comment by drwhut** [comment] 2022-11-28 16:09
Hmm... the problem is this can happen not just on Linux, but on Windows and macOS too. Plus, with the way I code, I want to deal with errors at the earliest possible place that they come up, so in this case, checking the output of `OS.get_system_dir` inside of `get_asset_paths`.

I don't particularly mind adding lots of checks for things, just see `Game.gd` as an example :stuck_out_tongue_closed_eyes:

**Comment by drwhut** [comment] 2022-11-28 16:26
Sorry, as in if `OS.get_system_dir` doesn't report what we expect, use `./` as a substitute on all platforms, so the `{DOCUMENTS}/TabletopClub` entry would become `./TabletopClub/assets`, for example.

**Closed** 2022-11-29 09:53 UTC
Labels: bug
