### ISSUE TITLE
Use custom font

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#279] opened 2023-04-30 15:33 UTC
**Is your feature request related to a problem? Please describe.**
There are already Chinese locales, which the default font doesn't support.

**Describe the solution you'd like**
Use custom fonts.

**Comment by drwhut** [comment] 2023-04-30 16:00
This is technically a duplicate of #212. As I said in that issue, fonts for unsupported characters (in this example, Chinese) will be added to the game once the language has been added as an option - and adding the ability to change the font in-game would mean having to support a wide variety of fonts in the UI, which is a daunting task.

**Closed by drwhut** 2023-04-30 16:00 UTC

**Comment by GrimPixel** [comment] 2023-04-30 17:57
That is just one of possible solutions. It can also be specifying the path to a font file.

**Comment by drwhut** [comment] 2023-04-30 18:45
Oh, that was what I thought you meant originally. What did you invision before?

**Comment by GrimPixel** [comment] 2023-05-01 03:25
I thought you meant it would be like the font manager on Linux, selecting one from all installed fonts.

**Comment by drwhut** [comment] 2023-05-01 03:41
No, the game comes bundled with two fonts, one for Latin characters and one for Cyrillic ones, and the engine automatically uses the correct font depending on the text being displayed. The game does not use system fonts whatsoever.

**Comment by GrimPixel** [comment] 2023-05-01 03:45
There current font Cabin doesn't even cover letters with caron.

Due to the problem of “CJK unification”, there should be one font for each one of the locales: cmn-CN-Hans, cmn-TW-Hant, yue-HK-Hant, jpn-JP-Jpan, kor-KR-Kore, which means adding hundreds megabytes to include a font like [Source Han Sans](https://github.com/adobe-fonts/source-han-sans)

**Comment by drwhut** [comment] 2023-05-01 04:08
If by carons you mean the diacritics above Latin letters, that should have been resolved with an update to the font files. If it isn't, could you show a screenshot of an example that doesn't work, and which languages it affects?

I knew about the sizes of CJK fonts already, which I've pretty much accepted is necessary for when those languages are added to the game.

**Comment by GrimPixel** [comment] 2023-05-01 04:17
Here are its glyphs: https://fonts.google.com/specimen/Cabin/glyphs

I mean, it is hard to find one font that covers all glyphs of a script.

Users may have already installed those fonts and I think there's no need to duplicate them.

**Comment by drwhut** [comment] 2023-05-01 04:29
My thinking is that if the default Latin font has all of the characters necessary for the languages that are available in the game, then it's OK - the font can always be changed in the future to accommodate unsupported characters.

The "may" in your statement is what's troubling me - I don't feel comfortable having to rely on the users environment for it to work properly. Plus, the method for reading system fonts will change from platform to platform, and I don't think Godot has the capability to do so yet, so it would all have to be manual.

Since the file sizes are so big, I'll have a look at how other games implement CJK fonts first before committing something that big to the git repository.
