### ISSUE TITLE
[Feature request] Ambience

### ISSUE THREAD

**Issue by GrimPixel** [drwhut/tabletop-club#186] opened 2022-12-05 04:35 UTC
Play multiple audio files as background music. They can be taken from websites like https://www.freesoundslibrary.com/

**Comment by elmodor** [comment] 2022-12-09 14:44
I think you would be able to do this with the speakers once they have the option to play music non spatial - then these can be used as background music.

Hence, duplicate of #170

**Closed** 2022-12-09 16:25 UTC

**Comment by elmodor** [comment] 2022-12-09 17:47
Yeah, just use multiple speakers? You can scale them down too so they wont use as much space
